
[build]
  command = "npm run build"
  publish = "dist"

# Redirects Netlify identity to avoid 404s
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify CMS configuration
[dev]
  framework = "vite"
  targetPort = 8080

# Identity settings for local development
[dev.identity]
  enable = true
