
backend:
  name: git-gateway
  branch: main # Branch to update

media_folder: "public/images/uploads" # Media will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media

collections:
  - name: "jobs" # Used in routes, e.g., /admin/collections/jobs
    label: "Jobs" # Used in the UI
    folder: "src/content/jobs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Company Name", name: "companyName", widget: "string", required: false}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Deadline", name: "deadline", widget: "string"}
      - {label: "Type", name: "type", widget: "select", options: ["Government", "Private"]}
      - {label: "Apply Link", name: "applyLink", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Company Logo", name: "companyLogo", widget: "image", required: false}
      - {label: "Publish Date", name: "createdAt", widget: "datetime"}
